spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Rent-a-bike
    username: postgres
    password: 915239
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  jwt:
    secret: ZnV0bmpoZXBicmJ0dmZubGppbmZ5dG55ZmlicmJjdmZueGZ2aW10aGphbmV2d3lhdm1qbGJrdGdlaGZweHJsamVyZmFsamRpZWJzc2hmZ3NvaGpheWRqZHdkZg==
    access: 1
    refresh: 1

rabbitmq:
  queues:
    application: applicationQueue
  keys:
    telegram: telegram
    email: email
  exchanges:
    main: Bicycle-exchange