### GET BIKES
GET http://localhost:8080/get_bikes

### GET CITIES
GET http://localhost:8080/get_cities

### POST APPLICAITON
POST http://localhost:8080/send_application
Content-Type: application/json

{
    "name": "hihi",
    "phone": "555555555",
    "email": "asdf@gmail.com",
    "city": 1,
    "comment": "hj",
    "bikeId": 1,
    "timestamp": 1698969727
}

### LOGIN
POST http://localhost:8080/admin/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin",
  "salt": "salt"
}

### GET APPLICATIONS
GET http://localhost:8080/admin/applications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlkIjowLCJleHAiOjE3MDE3MDY0NDh9.3QOaV1grkDxrU8j6gVh5GKkCtz2Rq2XsvFiGdT07M1leEKTm2Jf1SWwKi6LNrYR_QAYJ-BAwfacn9vagAYKRxQ

{
  "length": 10,
  "from": -2147483648,
  "to": -2147483648
}

### POST BIKE
POST http://localhost:8080/admin/bike
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlkIjowLCJleHAiOjE3MDE3MDY0NDh9.3QOaV1grkDxrU8j6gVh5GKkCtz2Rq2XsvFiGdT07M1leEKTm2Jf1SWwKi6LNrYR_QAYJ-BAwfacn9vagAYKRxQ

{
  "nameEn": "Eng",
  "namePl": "Pol",
  "nameUa": "Ukr",
  "nameRu": "Rus",
  "commentEn": "ComEng",
  "commentPl": "ComPol",
  "commentUa": "ComUkr",
  "commentRu": "ComRus",
  "rental": 250,
  "photos": [
    {
      "photoUrl": "www.example.com/11"
    },
    {
      "photoUrl": "www.example.com/21"
    }
  ]
}

### PATCH BIKE
PATCH http://localhost:8080/admin/bike


### DELETE BIKE
DELETE http://localhost:8080/admin/bike


### POST CITY
POST http://localhost:8080/admin/city


### DELETE CITY
DELETE http://localhost:8080/admin/city


### POST NEW_ADMIN
POST http://localhost:8080/admin/new_admin
Content-Type: application/json
Authorization: Bearer

{
  "login": "admin2",
  "password": "admin2",
  "salt": "salt"
}